
version: 2.1


jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build environment
          command: ./deploy-scripts/build-env.sh
      - run:
          name: Shellcheck
          command: ./deploy-scripts/shellcheck.sh
          when: always
      - run:
          name: Activate virtualenv
          command: echo "source env/bin/activate" >> $BASH_ENV
          when: always
workflows:
  version: 2.1
  build:
    jobs:
      -build-and-test